name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Setup Expo
        run: npm install -g eas-cli expo-cli
      
      - name: Install dependencies
        run: cd frontend && npm install
      
      - name: Build APK
        run: cd frontend && eas build --local --platform android --output=app.apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: frontend/app.apk
